select * from PRODUCTO 

--INSERTAR--
INSERT INTO PRODUCTO(PRODUCTO, PRECIO_UNITARIO, STOTCK, ESTADO)
  VALUES ('ARROZ','51.50','40',1);
  select * from PRODUCTO 

--MODIFICAR--
UPDATE PRODUCTO SET PRODUCTO = 'Arroz', PRECIO_UNITARIO='50', STOTCK='100'
WHERE IDPRODUCTO = '1'
select * from PRODUCTO 

--ACTUALIZAR_ELIMINAR--
UPDATE PRODUCTO SET ESTADO = '0'
WHERE IDPRODUCTO = '1'
select * from PRODUCTO 

--ELIMINAR--
DELETE FROM PRODUCTO WHERE IDPRODUCTO= '1'
select * from PRODUCTO 

